name: Tests
concurrency:
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
    paths:
      - src/**/*.py
      - tests/**/*.py

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@1.5.4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Linux & Mac setup
        run: |
          make setup-ci
          make setup-requirements
          make test
