name: Tests
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
    paths:
      - src/**/*.py
      - tests/**/*.py
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@1.5.4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          make setup-ci
          make setup-requirements
      - name: Run test
        run: |
          make test
